install-nshtools.js(1)
======================
R. S. Doiel <rsdoiel@gmail.com>
Version, 0.0.1x, 2010.03.03

copyright (c) 2010, R. S. Doiel, all rights reserved

Licensed under "The BSD License" described at http://opensource.org/licenses/bsd-license.php

== NAME

install-nshtools.js

== SYNPOSIS

This is a simple installer written using nshtools.js to install nshtools.js module and syncme.js. It has one option.

--Prefix::
        The prefix of where you want things installed.

nshtools needs to have node already installed. See link:http://nodejs.org[http://nodejs.org] for details.

== REQUIREMENTS

* node >= 1.30 footnote:[see link:http://nodejs.org[nodejs.org] for details.]

== GORY DETAILS

Typically node modules live in two place /usr/local/lib/node/libraries or $HOME/.node_libraries. If you write your own module or download someone elses and don't want to play with `process.paths` you wind up coping that module to where the rest of the modules live.  Likewise if you've written an application you wind up copying it to a "bin" folder on many Unix systems. install-nshtools.js does this for you based on the prefix path.

The default prefix path is your local home directory. The installer will fail if the directories don't exists. That is one of the ways it is simple. footnote:[$HOME/bin for syncme.js and $HOME/.node_libraries for nshtools.js, otherwise nshtools is put in $PREFIX/lib/node/libraries.]

== EXAMPLES

Install in your home directory footnote:[answer Y at the prompt].

.home
----
node install-nshtools.js
----

Install in /usr/local sing the `--prefix` option footnote:[answer Y at the prompt].

.prefix
----
node install-nshtools.js --prefix=/usr/local
----



