nshtools - README
=================
R. S. Doiel, <rsdoiel@gmail.com>
version 0.0.1x 2010.03.03

copyright (c) 2010, R. S. Doiel, all rights reserved

Licensed under "The BSD License" described at http://opensource.org/licenses/bsd-license.php

== NAME

nshtools - a node module to aimed to make it easier to write shell scripts


== SYNOPSIS

link:http://nodejs.org[node] provides an excellent platform for building network applications using non-blocking I/O. Now you can also do the same for system chores.  JavaScript can be a fast, concise language to write scripts in but if you're writing them for managing your system that was problematic until node.  Node has an excellent file system module (i.e. fs) and process module. It's largely CommonJS compliant. It's only missing a few higher level objects to make things as easy as Bash and that is what nshtools tries to address.

nshtools allows the creation of an object that supports

* common file operations like copy, move
* the work queue design pattern with prompts and tasks
* Simple support for long option command line parsing

It also supports two simple data structures with the DS object. I.e. nshtools.STACK and nshtools.QUEUE.

Checkout some of the link:examples[examples] or read link:nshtools.html[nshtools.html] (or link:nshtools.asciidoc[nshtools.asciidoc] if you're on github.com).
